### ISSUE TITLE
Would you please tag master?

### ISSUE THREAD

**Issue by calebwherry** [lvandeve/lodepng#10]
We would like to depend on lodepng for a project and would like to be able to check out specific tagged commits so that new changes to master will not necessarily break our build. We really enjoy using this project, thank you for your work.

**Comment by lvandeve** [comment]
Hello,

Some commits might be a security fix. Others might indeed break API for some new feature. Normally "head" should be the best version. Which commits would you like to be tagged after future commits? Is depending on a certain commit possible instead without a tag?

Thanks.

**Comment by robertdfrench** [comment]
Hi Lode,

We can depend on a specific commits, that would work very well. But tagging would allow you to give us a heads up about the semantic value of changes; mostly, "this change will probably not break your code" vs "this change will almost definitely break your code". Are you familiar with [Semantic Versioning](http://semver.org/)?

Thanks again for this library, it really is great.

**Comment by lvandeve** [comment]
Thanks a lot for pointing out semantic versioning. I will consider it, but currently I'll keep the current style due to time and other constraints preventing me from adopting a new paradigm at this time :). Hopefully depending on a commit will work for now, though to be honest an API-breaking commit will be really really rare (less than once a year), usually it's a bugfix or performance improvement instead (currently maybe once a month or so, after all it's mostly "done") so the head version might be the safest.
