### ISSUE TITLE
Would it be possible to support ARGB?

### ISSUE THREAD

**Issue by LinusU** [lvandeve/lodepng#15]
Hi, thank for a great library!

I was wondering if it would be possible to add `LCT_ARGB` to support storing the raw data with the order `ARGB` instead of `RGBA`. This is the format that [cairo][cairo] uses natively.

Having this would save me from doing the conversion in memory before hand, which I would guess is much slower.

Thanks!

[cairo]: http://cairographics.org

**Comment by LinusU** [comment]
Or maybe solve it by setting some other options/flags. `libpng` has

```text
           PNG_TRANSFORM_BGR           Flip RGB to BGR, RGBA
                                       to BGRA
           PNG_TRANSFORM_SWAP_ALPHA    Flip RGBA to ARGB or GA
                                       to AG
```

**Comment by lvandeve** [comment]
Hello,

The decision is for LodePNG to not do color conversions other than to exactly those models that exist in the PNG specification.

The reason for this is that there exist billions of possible color models, so converting to them would require a library of its own.

In your case, would it work for you to load to RGBA, and then use a for loop to swap the bytes to the order you want? This should not cost speed, since, if LodePNG did it internally it had to do the same thing anyway.

Just to give an idea about the amount of possible color models:
-any permutation of order of R, G, B and A, almost anything is getting used somewhere, ARGB, ABGR, RGBA, BGRA, ...
-whether or not A is present
-bits per pixel or per individual component (e.g. there exists 565 RGB and so on)
-whether alpha is premultiplied
-whether scanlines end at bytes or can end at bits in between, or even at a multiple of 4 bytes like BMP does
-whether it's mirrored (like BMP also does)
-and this didn't even get into YUV, HSL, and so on :)

So supporting anything outside of the PNG spec would mean having to support them all, and really that's outside of the scope of an image loading library imho :)

Regards,

-Lode

**Comment by LinusU** [comment]
Cool, yeah I actually realised after posting that those corresponded. Thats why I switched to options flags.

But I think that you are right, it shouldn't be the responsibility of lodepng to do that. Thank you for your time.
