### ISSUE TITLE
Lodepng fails to open valid png image

### ISSUE THREAD

**Issue by az-faro** [lvandeve/lodepng#186]
The included perfectly valid png image can not be opened by lodepng. Multiple Windows programs and GIMP has no issues opening it. Trying to open it in lodepng results in error 58 (adler32 check).

Test file: ![test.png](https://github.com/lvandeve/lodepng/assets/141626048/383c8b13-2559-4b23-af13-826bb4fcd2fb)

**Comment by lvandeve** [comment]
There is definitely something wrong with the PNG image.

Adler32 check can be ignored with lodepng (with the ignore_adler32 setting), but even when doing that there are still other errors in the image with IDAT chunks.

Firefox also can't shows it correctly for me, it begins rendering the image for progressively from the top and shows those contents, but at some point decides to stop and then displays a gray square with the URL in it instead of the image.

The imagemagick `convert` utility displays the following when trying to convert this image to another image format, which also shows something is truly wrong with this PNG:

```
$ convert 302563133-383c8b13-2559-4b23-af13-826bb4fcd2fb.png test.jpg
convert: bad adaptive filter value `302563133-383c8b13-2559-4b23-af13-826bb4fcd2fb.png' @ error/png.c/MagickPNGErrorHandler/1492.
convert: no images defined `test.jpg' @ error/convert.c/ConvertImageCommand/3362.
```

It's possible some image renderers are able to show something if it decodes the image line by line and already shows the first lines, since the error itself is only more towards the bottom part of the image. But LodePNG does not work line by line (yet, maybe some day...). So there is not much that can be done now.

**Comment by az-faro** [comment]
All I can say is that as stated above, all Windows image viewers I've used can open it and GIMP can open it. Neither of them shows corruption anywhere in the image. That doesn't mean the image isn't corrupt, but obviously they are in that case able to handle it gracefully and still decode the image.

**Comment by lvandeve** [comment]
In theory LodePNG also could decode everything it can up to the point in the image where the error happens, which would be most of the image since the error is somewhere more towards the bottom part of the image.

It doesn't have a setting for this (it only has some settings to ignore checksum errors and a few other edge case errors now).

Perhaps this is a feature to consider, some sort of "recover as much of the image as you can" setting. It's just that, when this is enabled, you can't know what you get, it's just lucky that in this image most pixels are still fine, in others an error may be very early.

**Comment by az-faro** [comment]
Well in that case I withdraw this issue as the image is obviously corrupt and not the fault of lodepng :)
