### ISSUE TITLE
[Not an issue] Error 56 with this png.

### ISSUE THREAD

**Issue by 0Camus0** [lvandeve/lodepng#23]
Hello, I got error 56 at loading the attached png. it seems that info_raw.bitdepth is zero even when info_png.color says it's 8 and also the format doesn't check, info_raw.colortype say is LCT_GREY but 
info_png.color says it's LCT_RGBA.

I'm using visual studio community 2015 in release config architecture x86.

![cube_xn](https://cloud.githubusercontent.com/assets/6864841/10907108/302dc6c8-81dc-11e5-87f9-d2e827a75db0.png)

**Comment by lvandeve** [comment]
Hi,

Which function do you use to load it? This error probably means the desired output color format is not one of the color formats supported by PNG. For LCT_GREY, it supports bit depths 1,2,4,8 or 16.

Does it work if you leave everything at the defaults? (Then it should output to RGBA, 8-bit per channel)

Thank you.

**Comment by lvandeve** [comment]
Actually, never mind that, please disregard the previous message.

The error means that it cannot do the conversion because the image is in color while the desired output is greyscale. It cannot convert from color to greyscale. This is on purpose: color-to-greyscale conversion causes information loss and lodepng usually refuses to discard information, it only converts to higher color models.

Color to greyscale conversion is not well-defined, there are many conversions such as (r+g+b)/3, (max(r,g,b)+min(r,g,b))/2, or 0.299*r + 0.587*g + 0.114*b, or others.

So the solution would be to load it to RGB color, and then choose one of the above conversions yourself and apply it to each pixel.

Would that work for you?

**Comment by 0Camus0** [comment]
Sorry I miss read the argument thinking it was an output parameter, I saw the example decode to get all the info, sorry, how can I erase this non issue.

Thanks for the response.
