### ISSUE TITLE
Little Endian 16bit output

### ISSUE THREAD

**Issue by eruffaldi** [lvandeve/lodepng#63]
LCT_GREY equivalent but with Little Endian

**Comment by lvandeve** [comment]
No plans to implement this, LodePNG only outputs to the color types that are defined in the PNG specification (https://www.w3.org/TR/2003/REC-PNG-20031110/) itself, including their endianness. 

Reason: there is a huge combinatory explosion of color types (endianness, ordering of RGB, amount of bits of each channel, ...). Supporting this is out of the scope of this PNG loading library.

But the good news it it's relatively easy to switch from one to the other with a single for loop. For example in this case switching the order of every pair of bytes. This can be done after decoding. There is no disadvantage of performance, because if it were done inside of LodePNG it would do the same for loop inside of it.

I hope that works.

**Comment by eruffaldi** [comment]
I have a patch for this but the statement "if it were done inside of LodePNG it would do the same for loop inside of it." conviced me

Thanks

-E
