### ISSUE TITLE
Discard color profile related chunks and metadata

### ISSUE THREAD

**Issue by MangaD** [lvandeve/lodepng#93]
Hello, this may not be an issue but more of a question. My problem is the following, I am trying to replace images in an SWF file, I load a PNG to memory and decode it, then convert RGBA to ARGB and everything appears to work great... except when I tried a PNG image with an embeded sRGB color profile. What happens is that Flash Player makes the transparent background white in this case. If I open the image in GIMP and export it, untick "Save background color", "Save resolution", "Save creation time", "Save color values from transparent pixels", "Save Exif data" and "Save color profile", basically getting rid of all the metadata and color profile, then it works as expected. Is there a way to do this with this library?

**Comment by lvandeve** [comment]
Hello MangaD,

LodePNG's decoder by default ignores background and color profile chunks, and the encoder by default does not add background or color profile chunks. But both can optionally read/attach/use some of those chunks. Would you like to use or to ignore those chunks? In what way exactly is LodePNG involved in the image with embedded profile in Flash Player? I didn't fully get it from the question

Is the background color white and does Flash Player happen to blit transparent images onto the background color rather than ignoring the bakcground color?

You can programmatically remove the background color chunk with LodePNG if you like. There is even way to do it without any full encoding/decoding using the chunk traversal functions. Would this help?

Kind regards,

-Lode

**Comment by MangaD** [comment]
Hello Ivandeve,

I would like to ignore those chunks. Flash player reads a picture from an ARGB array. I use LodePNG to read a PNG file and convert it to an ARGB array as follows:

```cpp
vector<uint8_t> argb;
unsigned width, height;
unsigned error = lodepng::decode(argb, width, height, imgBuf);
```

Where `imgBuf` contains a PNG file loaded to a `vector<uint8_t>`. I then proceed to replace the ARGB array in the SWF file and everything works as expected, except when I try an image that contains an sRGB color profile (accordingly to GIMP) and a transparent background. In this case, the image appears in flash player with a white background color in place of what should be a transparent background.

Perhaps the solution is exactly to remove the background color chunk with LodePNG. Can you tell me how can I do this?

Thank you,
MangaD

**Comment by lvandeve** [comment]
Does Flash Player itself ever get to see this sRGB color profile? Or does Flash Player only see that ARGB buffer?

How is the data stored in the SWF file? Since it's ARGB I assume it's not PNG?

Can you check if the "A" values of ARGB are 0 (transparent) where you expect them to be rather than 255?

Removing the background color chunk may be a solution if Flash Player sees that chunk, but if the only thing ever reading the background chunk is LodePNG itself, then it shouldn't matter because it already ignores it by default.

A simple way to remove it is: simply encode the RGBA buffer you got (not the ARGB one though since PNG doesn't use that ordering) with lodepng::encode. 

A method with higher performance (if you need that) but more complicated to implement is: starting from the original PNG image file (which you got in the vector<uint8_t>): copy over the first 8 bytes to a new vector, then starting at position 8 (using vector.data() + 8 to get the pointer it needs) use lodepng_chunk_next repeatedly to get each next chunk. Copy over that chunk to the new vector whenever its type is IHDR, PLTE, IDAT, tRNS or IEND, but do not copy it over when it's sRGB, bKGD, ... The type is gotten with lodepng_chunk_type_equals and the length to copy over is lodepng_chunk_length + 12. However this may be overkill to implement for your case :)

**Comment by MangaD** [comment]
Flash Player only gets to see the ARGB buffer.

I just tested with GIMP exporting PNG with different options, and unticking the checkbox "Save color values from transparent pixels" solved the problem. So the problem is not the color profile nor background color apparently.

I wonder how to do this with LodePNG?

**Comment by lvandeve** [comment]
Yes, LodePNG should set their alpha channel correctly to 0 if it's 0 in the image (so transparency supported), and will also read the RGB color values (even though those won't be shown since the alpha channel is 0, they still exist).

It depends on what gimp does, ultimately it has to save something to the PNG file format in a valid way here, if it uses the alpha channel and sets value 0 (transparent) in it, it should also be so when loaded with LodePNG, if gimp removes the alpha channel or sets values that were 0 to 255 in this case, then it'll also be 255 (opaque) when loaded in LodePNG.

What does gimp's PNG look like when opening in another application, say a web browser? Web browsers render the translucency correctly too normally so that could verify if the image is translucent or not (of course if the browser is showing it in a white page by default, requires putting it in an html page with other background color than white or using developer console to change the page's background to be able to see the difference)

Is there any way you could attach such a PNG image here so I could check out what's going on and how LodePNG reads it?

**Comment by MangaD** [comment]
All right, after reading your comment I figured something out, although my problem is not 100% solved yet. I just mimicked what GIMP does by not saving the color values of transparent pixels, and this is essentially what it does:
```cpp
// From the code above
// Convert RGBA to ARGB
for (size_t i = 0; i < argb.size(); i += 4) {
	iter_swap(argb.begin() + i, argb.begin() + i + 3);// AGBR
	iter_swap(argb.begin() + i + 1, argb.begin() + i + 2); // ABGR
	iter_swap(argb.begin() + i + 1, argb.begin() + i + 3); // ARGB
	// What GIMP does:
	if (argb[i] == 0) {
		argb[i+1] = 0;
		argb[i+2] = 0;
		argb[i+3] = 0;
	}
}
```
Web browsers show all images fine.

The PNG image in question is this one:
https://www.deviantart.com/henry-the-archer/art/Hero-Fighter-Lucas-730220558

The problem I'm having now is that pixels with some degree of transparency are showing fully white (https://imgur.com/zbP7aV0.png), but I begin to believe that this has nothing to do with LodePNG and instead on how Flash Player deals with the alpha channel. I'll do some research. Thanks a lot!

**Comment by MangaD** [comment]
The problem is fixed. SWF file format specification says that the RGB data should be multiplied by the alpha channel value, essentially this:
```cpp
 r = r * a / 255;
g = g * a / 255;
b = b * a / 255;
```
I will close this issue and rename its title.
